In [1]:
import numpy as np
import pandas as pd
import requests
import xlsxwriter
import math

import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import sklearn.metrics

from matplotlib import style
style.use('ggplot')

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

pd.options.display.max_columns = None

In [2]:
# import datetime
# import cryptocompare
# crypto_list = cryptocompare.get_historical_price_hour('ETH', 'USD', limit=17520, exchange='CCCAGG', toTs=datetime.datetime.now())
# #crypto_prices = pd.DataFrame(crypto_list, columns=['time', 'open', 'close', 'volumeto']).set_index('time')

In [3]:
token = 'e6d6ac2750a7fef37c62899d8496b3c46e90e5ec6e5a12393ce4abcb6d104050'
# api_url = f'https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETh,USDT,BNB,SOL&tsyms=USD,EUR&api_key={token}'
# print(api_url)

In [4]:
api_url = f'https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD'
print(api_url)

https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD

In [5]:
data = requests.get(api_url)
type(data)

requests.models.Response

In [6]:
data.status_code

200

In [230]:
# data = data.json()
# print(data)

In [391]:
# Start from time stamp 1717455600 as now
now = 1724300000
limit = 2000
change = 3600 * limit
timestamp = now - change

btc = []
for i in range(1, 10):
    api_url = f'https://min-api.cryptocompare.com/data/v2/histohour?fsym=BTC&tsym=USD&limit=2000&toTs={timestamp}&e=CCCAGG'
    data = requests.get(api_url)
    data = data.json()
    btc.append(data)
    timestamp = timestamp - change
    #print(api_url)
    
eth = []
timestamp = now - change
for i in range(1,10):
    api_url = f'https://min-api.cryptocompare.com/data/v2/histohour?fsym=ETH&tsym=USD&limit=2000&toTs={timestamp}&e=CCCAGG'
    data = requests.get(api_url)
    data = data.json()
    eth.append(data)
    timestamp = timestamp - change
    
bnb = []
timestamp = now - change
for i in range(1,10):
    api_url = f'https://min-api.cryptocompare.com/data/v2/histohour?fsym=BNB&tsym=USD&limit=2000&toTs={timestamp}&e=CCCAGG'
    data = requests.get(api_url)
    data = data.json()
    bnb.append(data)
    timestamp = timestamp - change

usdt = []
timestamp = now - change
for i in range(1,10):
    api_url = f'https://min-api.cryptocompare.com/data/v2/histohour?fsym=USDT&tsym=USD&limit=2000&toTs={timestamp}&e=CCCAGG'
    data = requests.get(api_url)
    data = data.json()
    usdt.append(data)
    timestamp = timestamp - change

sol = []
timestamp = now - change
for i in range(1,10):
    api_url = f'https://min-api.cryptocompare.com/data/v2/histohour?fsym=SOL&tsym=USD&limit=2000&toTs={timestamp}&e=CCCAGG'
    data = requests.get(api_url)
    data = data.json()
    sol.append(data)
    timestamp = timestamp - change

In [392]:
len(btc[0]["Data"]["Data"])

2001

In [393]:
btc_ = []
timestamp = now - change
for i in range(1,10):
    api_url = f'https://min-api.cryptocompare.com/data/exchange/histohour?tsym=BTC&limit=2000&toTs={timestamp}&e=CCCAGG'
    data = requests.get(api_url)
    data = data.json()
    btc_.append(data)
    timestamp = timestamp - change
    #print(api_url)

In [394]:
len(btc_[0]["Data"])

2001

In [395]:
btc__ = []
timestamp = now - change
for i in range(1,10):
    api_url = f'https://min-api.cryptocompare.com/data/symbol/histohour?fsym=BTC&tsym=USD&limit=2000&toTs={timestamp}&e=CCCAGG'
    data = requests.get(api_url)
    data = data.json()
    btc__.append(data)
    timestamp = timestamp - change
    #print(api_url)

In [396]:
len(btc__[0]["Data"])

2001

In [397]:
btc[0]["Data"]["Data"][0]

{'time': 1709899200,
 'high': 67825.73,
 'low': 67443.67,
 'open': 67796.83,
 'volumefrom': 827.36,
 'volumeto': 55925587.54,
 'close': 67548.45,
 'conversionType': 'direct',
 'conversionSymbol': ''}

In [398]:
btc__[0]["Data"][0]

{'time': 1709899200,
 'top_tier_volume_quote': 30910170.72,
 'top_tier_volume_base': 472742555.72,
 'top_tier_volume_total': 503652726.44,
 'cccagg_volume_quote': 31162801.92,
 'cccagg_volume_base': 280762430.49,
 'cccagg_volume_total': 311925232.41,
 'total_volume_quote': 1369000383.24,
 'total_volume_base': 1239002715.73,
 'total_volume_total': 2608003098.98}

In [399]:
btc__[1]["Data"][1]["top_tier_volume_quote"]

13618310.58

In [400]:
btc_time = []
btc_high = []
btc_low = []
btc_open = []
btc_volumefrom = []
btc_volumeto = []
btc_close = []

for i in range(len(btc)):
    for j in range(len(btc[i]["Data"]["Data"])):
        btc_time.append(btc[i]["Data"]["Data"][j]["time"])
        btc_high.append(btc[i]["Data"]["Data"][j]["high"])
        btc_low.append(btc[i]["Data"]["Data"][j]["low"])
        btc_open.append(btc[i]["Data"]["Data"][j]["open"])
        btc_volumefrom.append(btc[i]["Data"]["Data"][j]["volumefrom"])
        btc_volumeto.append(btc[i]["Data"]["Data"][j]["volumeto"])
        btc_close.append(btc[i]["Data"]["Data"][j]["close"])
        
btc1_time = []
btc1_volume = []

for i in range(len(btc_)):
    for j in range(len(btc_[i]["Data"])):
        btc1_time.append(btc_[i]["Data"][j]["time"])
        btc1_volume.append(btc_[i]["Data"][j]["volume"])
        
btc2_time = []
btc2_top_tier_volume_quote = []
btc2_top_tier_volume_base = []
btc2_top_tier_volume_total = []
btc2_cccagg_volume_quote = []
btc2_cccagg_volume_base = []
btc2_cccagg_volume_total = []
btc2_total_volume_quote = []
btc2_total_volume_base = []
btc2_total_volume_total = []

for i in range(len(btc__)):
    for j in range(len(btc__[i]["Data"])):
        btc2_time.append(btc__[i]["Data"][j]["time"])
        btc2_top_tier_volume_quote.append(btc__[i]["Data"][j]["top_tier_volume_quote"])
        btc2_top_tier_volume_base.append(btc__[i]["Data"][j]["top_tier_volume_base"])
        btc2_top_tier_volume_total.append(btc__[i]["Data"][j]["top_tier_volume_total"])
        btc2_cccagg_volume_quote.append(btc__[i]["Data"][j]["cccagg_volume_quote"])
        btc2_cccagg_volume_base.append(btc__[i]["Data"][j]["cccagg_volume_base"])
        btc2_cccagg_volume_total.append(btc__[i]["Data"][j]["cccagg_volume_total"])
        btc2_total_volume_quote.append(btc__[i]["Data"][j]["total_volume_quote"])
        btc2_total_volume_base.append(btc__[i]["Data"][j]["total_volume_base"])
        btc2_total_volume_total.append(btc__[i]["Data"][j]["total_volume_total"])
        
eth_time = []
eth_open = []
eth_close = []

for i in range(len(eth)):
    for j in range(len(eth[i]["Data"]["Data"])):
        eth_time.append(eth[i]["Data"]["Data"][j]["time"])
        eth_open.append(eth[i]["Data"]["Data"][j]["open"])
        eth_close.append(eth[i]["Data"]["Data"][j]["close"])
        
bnb_time = []
bnb_open = []
bnb_close = []

for i in range(len(bnb)):
    for j in range(len(bnb[i]["Data"]["Data"])):
        bnb_time.append(bnb[i]["Data"]["Data"][j]["time"])
        bnb_open.append(bnb[i]["Data"]["Data"][j]["open"])
        bnb_close.append(bnb[i]["Data"]["Data"][j]["close"])
        
usdt_time = []
usdt_open = []
usdt_close = []

for i in range(len(usdt)):
    for j in range(len(usdt[i]["Data"]["Data"])):
        usdt_time.append(usdt[i]["Data"]["Data"][j]["time"])
        usdt_open.append(usdt[i]["Data"]["Data"][j]["open"])
        usdt_close.append(usdt[i]["Data"]["Data"][j]["close"])
        
sol_time = []
sol_open = []
sol_close = []

for i in range(len(sol)):
    for j in range(len(sol[i]["Data"]["Data"])):
        sol_time.append(sol[i]["Data"]["Data"][j]["time"])
        sol_open.append(sol[i]["Data"]["Data"][j]["open"])
        sol_close.append(sol[i]["Data"]["Data"][j]["close"])

In [401]:
btc_df = pd.DataFrame(
    {'datetime': btc_time,
     'high': btc_high,
     'low': btc_low,
     'open': btc_open,
     'volumefrom': btc_volumefrom,
     'volumeto': btc_volumeto,
     'close': btc_close
    })

btc1_df = pd.DataFrame(
    {'datetime': btc1_time,
     'hourly_volume': btc1_volume
    })

btc2_df = pd.DataFrame(
    {'datetime': btc2_time,
     'top_tier_volume_quote': btc2_top_tier_volume_quote,
     'top_tier_volume_base': btc2_top_tier_volume_base,
     'top_tier_volume_total': btc2_top_tier_volume_total,
     'cccagg_volume_quote': btc2_cccagg_volume_quote,
     'cccagg_volume_base': btc2_cccagg_volume_base,
     'cccagg_volume_total': btc2_cccagg_volume_total,
     'total_volume_quote': btc2_total_volume_quote,
     'total_volume_base': btc2_total_volume_base,
     'total_volume_total': btc2_total_volume_total
    })

eth_df = pd.DataFrame(
    {'datetime': eth_time,
     'open': eth_open,
     'close': eth_close
    })

bnb_df = pd.DataFrame(
    {'datetime': bnb_time,
     'open': bnb_open,
     'close': bnb_close
    })

usdt_df = pd.DataFrame(
    {'datetime': usdt_time,
     'open': usdt_open,
     'close': usdt_close
    })

sol_df = pd.DataFrame(
    {'datetime': sol_time,
     'open': sol_open,
     'close': sol_close
    })

In [402]:
sol_df.duplicated().sum()

8

In [403]:
df_list = [btc_df, btc1_df, btc2_df, eth_df, bnb_df, usdt_df, sol_df]
for each in df_list:
    each.drop_duplicates(inplace=True)
    each.reset_index(drop = True, inplace = True)

In [404]:
final = btc_df.copy()
final = pd.merge(final, btc1_df, how = "left", on = "datetime")
final = pd.merge(final, btc2_df, how = "left", on = "datetime")

In [405]:
final["eth_open"] = eth_df["open"]
final["eth_close"] = eth_df["close"]
final["bnb_open"] = bnb_df["open"]
final["bnb_close"] = bnb_df["close"]
final["usdt_open"] = usdt_df["open"]
final["usdt_close"] = usdt_df["close"]
final["sol_open"] = sol_df["open"]
final["sol_close"] = sol_df["close"]

In [406]:
final['datetime'] = pd.to_datetime(final['datetime'], unit='s')

In [407]:
final.sort_values(by = ['datetime'], inplace = True)
final.reset_index(drop = True, inplace = True)

In [408]:
final.duplicated().sum()

0

In [409]:
final

,datetime,high,low,open,volumefrom,volumeto,close,hourly_volume,top_tier_volume_quote,top_tier_volume_base,top_tier_volume_total,cccagg_volume_quote,cccagg_volume_base,cccagg_volume_total,total_volume_quote,total_volume_base,total_volume_total,eth_open,eth_close,bnb_open,bnb_close,usdt_open,usdt_close,sol_open,sol_close
0,2022-05-11 20:00:00,29575.44,28302.10,29294.85,12546.53,3.629059e+08,28381.05,167525.22,2.895957e+08,2.010590e+09,2.300185e+09,2.132561e+08,1.317591e+09,1.530847e+09,3.148131e+08,6.212428e+09,6.527242e+09,2111.34,2035.44,270.60,266.24,0.9977,0.9973,47.72,43.97
1,2022-05-11 21:00:00,29062.60,28087.41,28381.05,10480.22,2.981395e+08,29033.40,149909.15,2.851965e+08,2.071564e+09,2.356760e+09,2.101435e+08,1.369293e+09,1.579437e+09,3.105886e+08,6.065145e+09,6.375733e+09,2035.44,2089.41,266.24,269.53,0.9973,0.9978,43.97,46.99
2,2022-05-11 22:00:00,29182.25,28474.63,29033.40,5513.78,1.589880e+08,28792.95,115264.57,1.902491e+08,1.432327e+09,1.622577e+09,1.464666e+08,8.188565e+08,9.653228e+08,2.169687e+08,5.422037e+09,5.639006e+09,2089.41,2078.91,269.53,269.77,0.9966,0.9962,46.99,47.68
3,2022-05-11 23:00:00,29019.79,28550.67,28792.95,3651.01,1.050706e+08,29017.21,87264.50,1.354793e+08,1.029173e+09,1.164652e+09,1.043824e+08,5.740295e+08,6.784119e+08,1.584795e+08,5.352560e+09,5.511040e+09,2078.91,2077.83,269.77,270.59,0.9962,0.9959,47.68,50.82
4,2022-05-12 00:00:00,30085.67,28913.99,29017.21,7054.05,2.087661e+08,29750.31,130759.51,2.409674e+08,1.691784e+09,1.932752e+09,1.694271e+08,1.030014e+09,1.199441e+09,2.658333e+08,5.441226e+09,5.707059e+09,2077.83,2144.86,270.59,275.89,0.9971,0.9976,50.82,51.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17996,2024-05-30 16:00:00,68689.45,68375.52,68515.99,903.01,6.185794e+07,68666.60,17823.69,1.201734e+07,4.150450e+08,4.270616e+08,1.229063e+07,2.730843e+08,2.853750e+08,4.614258e+07,6.713479e+08,7.174904e+08,3775.28,3787.19,596.57,596.92,0.9998,0.9998,168.43,169.75
17997,2024-05-30 17:00:00,69520.94,68656.75,68666.60,2544.09,1.759271e+08,69340.86,27005.46,2.748048e+07,9.362715e+08,9.637520e+08,2.810524e+07,7.090838e+08,7.371890e+08,8.406400e+07,1.580105e+09,1.664169e+09,3787.19,3810.35,596.92,599.11,0.9998,1.0000,169.75,171.30
17998,2024-05-30 18:00:00,69434.32,69086.25,69340.86,1243.56,8.613219e+07,69373.21,17375.74,1.954451e+07,5.031528e+08,5.226973e+08,2.003706e+07,3.406509e+08,3.606887e+08,6.217366e+07,8.704458e+08,9.326194e+08,3810.35,3814.60,599.11,600.08,1.0000,1.0000,171.30,170.76
17999,2024-05-30 19:00:00,69377.03,68437.59,69373.21,1949.62,1.343113e+08,68663.82,20134.98,1.891620e+07,6.730586e+08,6.919748e+08,1.899516e+07,4.644812e+08,4.834764e+08,6.482826e+07,1.043574e+09,1.108402e+09,3814.60,3761.35,600.08,597.17,1.0000,1.0000,170.76,168.37
18000,2024-05-30 20:00:00,68666.65,68057.25,68663.82,908.03,6.206350e+07,68474.42,19897.33,1.616476e+07,5.360753e+08,5.522393e+08,1.586484e+07,3.569750e+08,3.728398e+08,6.121408e+07,8.748805e+08,9.360939e+08,3761.35,3737.76,597.17,594.08,1.0000,1.0000,168.37,167.22

In [419]:
final.to_csv("Data/bitcoin.csv")

In [4]:
data = pd.read_csv(r"Data/bitcoin.csv")

In [5]:
data.columns

Index(['Unnamed: 0', 'datetime', 'high', 'low', 'open', 'volumefrom',
       'volumeto', 'close', 'hourly_volume', 'top_tier_volume_quote',
       'top_tier_volume_base', 'top_tier_volume_total', 'cccagg_volume_quote',
       'cccagg_volume_base', 'cccagg_volume_total', 'total_volume_quote',
       'total_volume_base', 'total_volume_total', 'eth_open', 'eth_close',
       'bnb_open', 'bnb_close', 'usdt_open', 'usdt_close', 'sol_open',
       'sol_close'],
      dtype='object')

In [6]:
data =  data[['datetime', 'high', 'low', 'open', 'volumefrom','volumeto', 'close', 'hourly_volume']]

In [8]:
data

,datetime,high,low,open,volumefrom,volumeto,close,hourly_volume
0,2022-05-11 20:00:00,29575.44,28302.10,29294.85,12546.53,3.629059e+08,28381.05,167525.22
1,2022-05-11 21:00:00,29062.60,28087.41,28381.05,10480.22,2.981395e+08,29033.40,149909.15
2,2022-05-11 22:00:00,29182.25,28474.63,29033.40,5513.78,1.589880e+08,28792.95,115264.57
3,2022-05-11 23:00:00,29019.79,28550.67,28792.95,3651.01,1.050706e+08,29017.21,87264.50
4,2022-05-12 00:00:00,30085.67,28913.99,29017.21,7054.05,2.087661e+08,29750.31,130759.51
...,...,...,...,...,...,...,...,...
17996,2024-05-30 16:00:00,68689.45,68375.52,68515.99,903.01,6.185794e+07,68666.60,17823.69
17997,2024-05-30 17:00:00,69520.94,68656.75,68666.60,2544.09,1.759271e+08,69340.86,27005.46
17998,2024-05-30 18:00:00,69434.32,69086.25,69340.86,1243.56,8.613219e+07,69373.21,17375.74
17999,2024-05-30 19:00:00,69377.03,68437.59,69373.21,1949.62,1.343113e+08,68663.82,20134.98
18000,2024-05-30 20:00:00,68666.65,68057.25,68663.82,908.03,6.206350e+07,68474.42,19897.33